---
# Prepare node for LXC usage

- name: Install lxc packages
  ansible.builtin.package:
    name:
      - lxc
      - lxcfs
      - tar
      - python3-lxc
    state: "{{ lxc_version }}"

- name: Create default lxc containers config
  ansible.builtin.template:
    src: etc-lxc-default.conf.j2
    dest: /etc/lxc/default.conf

- name: Enable and start lxc service
  ansible.builtin.service:
    name: lxc
    enabled: yes

- name: Add lxcbr1 bridge
  community.general.nmcli:
    conn_name: lxcbr1
    ifname: lxcbr1
    type: bridge
    state: present

- name: Add bridge slave connection
  community.general.nmcli:
    conn_name: "{{ CONNECTION_NAME }}"
    ifname: "{{ CONNECTION_NAME }}"
    type: bridge-slave
    master: lxcbr1
    state: present

- name: up lxcbr1 connection
  community.general.nmcli:
    conn_name: lxcbr1
    state: present
    
- name: Insert/Update configuration "/etc/sysctl.conf"
  ansible.builtin.blockinfile:
    block: |
      fs.inotify.max_user_instances=1024
      vm.swappiness=10
      vm.vfs_cache_pressure=50
    path: /etc/sysctl.conf
    marker: "#  {mark} sysctl ansible config  #"

- name: Copy lxc template
  ansible.builtin.copy:
    src: lxc-tar
    dest: /usr/share/lxc/templates/lxc-tar
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Reload sysctl settings
  ansible.builtin.command: sysctl -p
  register: sysctl_reload
  changed_when: sysctl_reload.stdout != ""
  ignore_errors: yes

- name: Reload all network connections
  command: nmcli connection reload